server:
  port: 8081

spring:
  #数据库连接 spring:，已加密
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 原url: jdbc:mysql://8.141.48.181:3306/floating-population?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    url: ENC(DTOFf0EfYZad84406ZczYXT2zXZE+/obb0HRGGq+xGomMNA4nlGEujav2ct0RV8wcnKG5SHx/PxEWB4mEgo95L7x3L6KFRLng4/EhINXXyanMWC+/IwnRSCS6JSDFSu7+Xmu3zlWAIgr6YNlZOb45ScL75TpH7QHBqah+OVvUtleFChSRATn2g==)
    username: ENC(u8urMeaoOrS3kTyI6G140A6n4OUbLNFL)
    password: ENC(fB55Vo5yN1moCRIm/gBn5AxjQbDWu8NK)

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' #默认开启

      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true  #开启页面表单的REST功能
mybatis:
  mapper-locations: classpath:mapper/*.xml # 扫描所有mybatis的xml文件
  #  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
#  configuration:  #被 mybatis-plus 管理
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
#    map-underscore-to-camel-case: true # 开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn。

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
    map-underscore-to-camel-case: true # 开启驼峰命名

files:
  upload:
    path: /Users/huxinzhi/Developer/GitHub/Graduation-Design/files/



# 加密工具（换成java类了，生成一个 jasyptStringEncryptor 组件放入SpringBoot中，在配置类中 JasyptConfig.java）
#jasypt:
#  encryptor:
#    # 在生产环境中，建议使用如下方式配置密钥，避免密钥泄露
#    password: huxinzhi # java -jar -Djasypt.encryptor.password=huxinzhi
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator